import os
import sqlite3
import logging
from io import BytesIO
from telegram import Update
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes
from stability_sdk import client
import stability_sdk.interfaces.gooseai.generation.generation_pb2 as generation

# Ambil dari Railway Environment Variables
TOKEN = os.getenv("7260363453:AAHkl23HlxDZxpIeTPI-L0NsNbgbNnxogzM")
STABILITY_API_KEY = os.getenv("STABILITY_KEY")

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Stability AI client
stability_api = client.StabilityInference(
    key=STABILITY_API_KEY,
    verbose=False,
    engine="stable-diffusion-xl-1024-v1-0",
)

def init_db():
    conn = sqlite3.connect('brain.db')
    c = conn.cursor()
    c.execute('''CREATE TABLE IF NOT EXISTS qa (
                 question TEXT PRIMARY KEY,
                 answer TEXT,
                 image_prompt TEXT)''')
    conn.commit()
    conn.close()

def learn(question: str, answer: str = None, image_prompt: str = None):
    conn = sqlite3.connect('brain.db')
    c = conn.cursor()
    c.execute("INSERT OR REPLACE INTO qa (question, answer, image_prompt) VALUES (?, ?, ?)",
              (question.lower(), answer or "", image_prompt or ""))
    conn.commit()
    conn.close()

def get_qa(question: str):
    conn = sqlite3.connect('brain.db')
    c = conn.cursor()
    c.execute("SELECT answer, image_prompt FROM qa WHERE question = ?", (question.lower(),))
    row = c.fetchone()
    conn.close()
    return (row[0], row[1]) if row else (None, None)

async def generate_image(prompt: str, update: Update):
    try:
        answers = stability_api.generate(prompt=prompt, width=1024, height=1024, steps=30)
        for resp in answers:
            for artifact in resp.artifacts:
                if artifact.type == generation.ARTIFACT_IMAGE:
                    image = BytesIO(artifact.binary)
                    image.name = "image.png"
                    await update.message.reply_photo(photo=image, caption="Generated by Stability AI")
                    return
        await update.message.reply_text("Gagal generate gambar")
    except Exception as e:
        logger.error(e)
        await update.message.reply_text("Error generate gambar (cek API key atau kredit)")

# === Handler Telegram ===
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Bot pintar yang bisa kamu ajarin text & gambar!\n\n"
        "Text  → bot, kalau ditanya apa kabar jawab Baik dong!\n"
        "Gambar→ bot, kalau ditanya gambar naga generate a dragon in cyberpunk city, ultra detailed"
    )

async def hapus(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not context.args:
        await update.message.reply_text("Gunakan: /hapus pertanyaan")
        return
    q = " ".join(context.args).lower()
    conn = sqlite3.connect('brain.db')
    c = conn.cursor()
    c.execute("DELETE FROM qa WHERE question=?", (q,))
    if c.rowcount > 0:
        await update.message.reply_text(f"Berhasil hapus: {q})
    else:
        await update.message.reply_text("Tidak ketemu")
    conn.commit()
    conn.close()

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text.strip()
    lower = text.lower()

    if lower.startswith(("bot,", "bot ", "bot:")):
        # === MODE AJARIN ===
        try:
            if "gambar" in lower and "generate" in lower:
                # gambar
                bagian = text.split("gambar", 1)[1]
                q_prompt = bagian.split("generate", 1)
                deskripsi = q_prompt[0].strip(" ?.!,")
                prompt_ai = q_prompt[1].strip()
                learn(deskripsi, image_prompt=prompt_ai)
                await update.message.reply_text(f"OK! \"gambar {deskripsi}\" → akan generate gambar")
                return

            # text biasa
            bagian = text.split("kalau ditanya", 1)[1]
            q_a = bagian.split("jawab", 1)
            question = q_a[0].strip(" ?.!,")
            answer = q_a[1].strip()
            learn(question, answer=answer)
            await update.message.reply_text(f"OK! \"{question}\" → \"{answer}\"")
        except:
            await update.message.reply_text("Format salah")
        return

    # === MODE JAWAB ===
    answer, img_prompt = get_qa(lower)
    if "gambar" in lower and img_prompt:
        await update.message.reply_text("Sedang menggambar...")
        await generate_image(img_prompt, update)
    elif answer:
        await update.message.reply_text(answer)
    else:
        await update.message.reply_text("Aku belum tahu. Ajari aku ya!")

def main():
    init_db()
    app = Application.builder().token(TOKEN).build()

    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("hapus", hapus))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))

    print("Bot berjalan di Railway!")
    app.run_polling(drop_pending_updates=True)

if __name__ == "__main__":
    main()
